'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
'
Namespace B_EKIS_SP_TESTWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SI_TESTWS_OUTSyncBinding", [Namespace]:="http://mfcr.cz/iissp/risre/common"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(IndikatorXmlType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(CenaType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(IdentifikatorType))>  _
    Partial Public Class SI_TESTWS_OUTSyncService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SI_TESTWS_OUTSyncOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IISSPTestApplication.My.MySettings.Default.IISSPTestApplication_B_EKIS_SP_TESTWS_SI_TESTWS_OUTSyncService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SI_TESTWS_OUTSyncCompleted As SI_TESTWS_OUTSyncCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Sub SI_TESTWS_OUTSync(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")> ByRef Envelope As EnvelopeType)
            Dim results() As Object = Me.Invoke("SI_TESTWS_OUTSync", New Object() {Envelope})
            Envelope = CType(results(0),EnvelopeType)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SI_TESTWS_OUTSyncAsync(ByVal Envelope As EnvelopeType)
            Me.SI_TESTWS_OUTSyncAsync(Envelope, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SI_TESTWS_OUTSyncAsync(ByVal Envelope As EnvelopeType, ByVal userState As Object)
            If (Me.SI_TESTWS_OUTSyncOperationCompleted Is Nothing) Then
                Me.SI_TESTWS_OUTSyncOperationCompleted = AddressOf Me.OnSI_TESTWS_OUTSyncOperationCompleted
            End If
            Me.InvokeAsync("SI_TESTWS_OUTSync", New Object() {Envelope}, Me.SI_TESTWS_OUTSyncOperationCompleted, userState)
        End Sub
        
        Private Sub OnSI_TESTWS_OUTSyncOperationCompleted(ByVal arg As Object)
            If (Not (Me.SI_TESTWS_OUTSyncCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SI_TESTWS_OUTSyncCompleted(Me, New SI_TESTWS_OUTSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class EnvelopeType
        
        Private envelopeHeaderField As EnvelopeHeaderType
        
        Private envelopeBodyField As EnvelopeBodyType
        
        Private envelopeFooterField As EnvelopeFooterType
        
        '''<remarks/>
        Public Property EnvelopeHeader() As EnvelopeHeaderType
            Get
                Return Me.envelopeHeaderField
            End Get
            Set
                Me.envelopeHeaderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EnvelopeBody() As EnvelopeBodyType
            Get
                Return Me.envelopeBodyField
            End Get
            Set
                Me.envelopeBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EnvelopeFooter() As EnvelopeFooterType
            Get
                Return Me.envelopeFooterField
            End Get
            Set
                Me.envelopeFooterField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class EnvelopeHeaderType
        
        Private transactionIdField As MessageIdType
        
        Private referenceTransactionIdField As MessageIdType
        
        Private dateTimeCreatedField As DatumCasType
        
        Private senderField As SenderSubjectType
        
        Private recipientField As RecipientSubjectType
        
        Private authenticationField As AuthenticationType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property TransactionId() As MessageIdType
            Get
                Return Me.transactionIdField
            End Get
            Set
                Me.transactionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property ReferenceTransactionId() As MessageIdType
            Get
                Return Me.referenceTransactionIdField
            End Get
            Set
                Me.referenceTransactionIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DateTimeCreated() As DatumCasType
            Get
                Return Me.dateTimeCreatedField
            End Get
            Set
                Me.dateTimeCreatedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sender() As SenderSubjectType
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Recipient() As RecipientSubjectType
            Get
                Return Me.recipientField
            End Get
            Set
                Me.recipientField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Authentication() As AuthenticationType
            Get
                Return Me.authenticationField
            End Get
            Set
                Me.authenticationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class MessageIdType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(FaxTelefonCisloType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(EmailType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SubjektICOType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SubjectIdType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ModuleType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(PersonIdType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(MessageIdType)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class IdentifikatorType
        
        Private schemaIDField As String
        
        Private schemaSpravceIDField As String
        
        Private jazykKodField As jazykType
        
        Private jazykKodFieldSpecified As Boolean
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property schemaID() As String
            Get
                Return Me.schemaIDField
            End Get
            Set
                Me.schemaIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property schemaSpravceID() As String
            Get
                Return Me.schemaSpravceIDField
            End Get
            Set
                Me.schemaSpravceIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property jazykKod() As jazykType
            Get
                Return Me.jazykKodField
            End Get
            Set
                Me.jazykKodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property jazykKodSpecified() As Boolean
            Get
                Return Me.jazykKodFieldSpecified
            End Get
            Set
                Me.jazykKodFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Public Enum jazykType
        
        '''<remarks/>
        aa
        
        '''<remarks/>
        ab
        
        '''<remarks/>
        af
        
        '''<remarks/>
        am
        
        '''<remarks/>
        ar
        
        '''<remarks/>
        [as]
        
        '''<remarks/>
        ay
        
        '''<remarks/>
        az
        
        '''<remarks/>
        ba
        
        '''<remarks/>
        be
        
        '''<remarks/>
        bg
        
        '''<remarks/>
        bh
        
        '''<remarks/>
        bi
        
        '''<remarks/>
        bn
        
        '''<remarks/>
        bo
        
        '''<remarks/>
        br
        
        '''<remarks/>
        ca
        
        '''<remarks/>
        co
        
        '''<remarks/>
        cs
        
        '''<remarks/>
        cy
        
        '''<remarks/>
        da
        
        '''<remarks/>
        de
        
        '''<remarks/>
        dz
        
        '''<remarks/>
        el
        
        '''<remarks/>
        en
        
        '''<remarks/>
        eo
        
        '''<remarks/>
        es
        
        '''<remarks/>
        et
        
        '''<remarks/>
        eu
        
        '''<remarks/>
        fa
        
        '''<remarks/>
        fi
        
        '''<remarks/>
        fj
        
        '''<remarks/>
        fo
        
        '''<remarks/>
        fr
        
        '''<remarks/>
        fy
        
        '''<remarks/>
        ga
        
        '''<remarks/>
        gd
        
        '''<remarks/>
        gl
        
        '''<remarks/>
        gn
        
        '''<remarks/>
        gu
        
        '''<remarks/>
        ha
        
        '''<remarks/>
        he
        
        '''<remarks/>
        hi
        
        '''<remarks/>
        hr
        
        '''<remarks/>
        hu
        
        '''<remarks/>
        hy
        
        '''<remarks/>
        ia
        
        '''<remarks/>
        ie
        
        '''<remarks/>
        ik
        
        '''<remarks/>
        id
        
        '''<remarks/>
        [is]
        
        '''<remarks/>
        it
        
        '''<remarks/>
        iu
        
        '''<remarks/>
        ja
        
        '''<remarks/>
        jv
        
        '''<remarks/>
        ka
        
        '''<remarks/>
        kk
        
        '''<remarks/>
        kl
        
        '''<remarks/>
        km
        
        '''<remarks/>
        kn
        
        '''<remarks/>
        ko
        
        '''<remarks/>
        ks
        
        '''<remarks/>
        ku
        
        '''<remarks/>
        ky
        
        '''<remarks/>
        la
        
        '''<remarks/>
        ln
        
        '''<remarks/>
        lo
        
        '''<remarks/>
        lt
        
        '''<remarks/>
        lv
        
        '''<remarks/>
        mg
        
        '''<remarks/>
        mi
        
        '''<remarks/>
        mk
        
        '''<remarks/>
        ml
        
        '''<remarks/>
        mn
        
        '''<remarks/>
        mo
        
        '''<remarks/>
        mr
        
        '''<remarks/>
        ms
        
        '''<remarks/>
        mt
        
        '''<remarks/>
        my
        
        '''<remarks/>
        na
        
        '''<remarks/>
        ne
        
        '''<remarks/>
        nl
        
        '''<remarks/>
        no
        
        '''<remarks/>
        oc
        
        '''<remarks/>
        om
        
        '''<remarks/>
        [or]
        
        '''<remarks/>
        pa
        
        '''<remarks/>
        pl
        
        '''<remarks/>
        ps
        
        '''<remarks/>
        pt
        
        '''<remarks/>
        qu
        
        '''<remarks/>
        rm
        
        '''<remarks/>
        rn
        
        '''<remarks/>
        ro
        
        '''<remarks/>
        ru
        
        '''<remarks/>
        rw
        
        '''<remarks/>
        sa
        
        '''<remarks/>
        sd
        
        '''<remarks/>
        sg
        
        '''<remarks/>
        sh
        
        '''<remarks/>
        si
        
        '''<remarks/>
        sk
        
        '''<remarks/>
        sl
        
        '''<remarks/>
        sm
        
        '''<remarks/>
        sn
        
        '''<remarks/>
        so
        
        '''<remarks/>
        sq
        
        '''<remarks/>
        sr
        
        '''<remarks/>
        ss
        
        '''<remarks/>
        st
        
        '''<remarks/>
        su
        
        '''<remarks/>
        sv
        
        '''<remarks/>
        sw
        
        '''<remarks/>
        ta
        
        '''<remarks/>
        te
        
        '''<remarks/>
        tg
        
        '''<remarks/>
        th
        
        '''<remarks/>
        ti
        
        '''<remarks/>
        tk
        
        '''<remarks/>
        tl
        
        '''<remarks/>
        tn
        
        '''<remarks/>
        [to]
        
        '''<remarks/>
        tr
        
        '''<remarks/>
        ts
        
        '''<remarks/>
        tt
        
        '''<remarks/>
        tw
        
        '''<remarks/>
        ug
        
        '''<remarks/>
        uk
        
        '''<remarks/>
        ur
        
        '''<remarks/>
        uz
        
        '''<remarks/>
        vi
        
        '''<remarks/>
        vo
        
        '''<remarks/>
        wo
        
        '''<remarks/>
        xh
        
        '''<remarks/>
        yi
        
        '''<remarks/>
        yo
        
        '''<remarks/>
        za
        
        '''<remarks/>
        zh
        
        '''<remarks/>
        zu
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ObjectType
        
        Private anyField() As System.Xml.XmlNode
        
        Private idField As String
        
        Private mimeTypeField As String
        
        Private encodingField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MimeType() As String
            Get
                Return Me.mimeTypeField
            End Get
            Set
                Me.mimeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Encoding() As String
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SPKIDataType
        
        Private sPKISexpField()() As Byte
        
        Private anyField As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType:="base64Binary")>  _
        Public Property SPKISexp() As Byte()()
            Get
                Return Me.sPKISexpField
            End Get
            Set
                Me.sPKISexpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class PGPDataType
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("PGPKeyID", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType1()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>  _
        Item
        
        '''<remarks/>
        PGPKeyID
        
        '''<remarks/>
        PGPKeyPacket
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509IssuerSerialType
        
        Private x509IssuerNameField As String
        
        Private x509SerialNumberField As String
        
        '''<remarks/>
        Public Property X509IssuerName() As String
            Get
                Return Me.x509IssuerNameField
            End Get
            Set
                Me.x509IssuerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property X509SerialNumber() As String
            Get
                Return Me.x509SerialNumberField
            End Get
            Set
                Me.x509SerialNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class X509DataType
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("X509CRL", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("X509Certificate", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", GetType(X509IssuerSerialType)),  _
         System.Xml.Serialization.XmlElementAttribute("X509SKI", GetType(Byte()), DataType:="base64Binary"),  _
         System.Xml.Serialization.XmlElementAttribute("X509SubjectName", GetType(String)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>  _
        Item
        
        '''<remarks/>
        X509CRL
        
        '''<remarks/>
        X509Certificate
        
        '''<remarks/>
        X509IssuerSerial
        
        '''<remarks/>
        X509SKI
        
        '''<remarks/>
        X509SubjectName
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RetrievalMethodType
        
        Private transformsField() As TransformType
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class TransformType
        
        Private itemsField() As Object
        
        Private textField() As String
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("XPath", GetType(String))>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class RSAKeyValueType
        
        Private modulusField() As Byte
        
        Private exponentField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Modulus() As Byte()
            Get
                Return Me.modulusField
            End Get
            Set
                Me.modulusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Exponent() As Byte()
            Get
                Return Me.exponentField
            End Get
            Set
                Me.exponentField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DSAKeyValueType
        
        Private pField() As Byte
        
        Private qField() As Byte
        
        Private gField() As Byte
        
        Private yField() As Byte
        
        Private jField() As Byte
        
        Private seedField() As Byte
        
        Private pgenCounterField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property P() As Byte()
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Q() As Byte()
            Get
                Return Me.qField
            End Get
            Set
                Me.qField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property G() As Byte()
            Get
                Return Me.gField
            End Get
            Set
                Me.gField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Y() As Byte()
            Get
                Return Me.yField
            End Get
            Set
                Me.yField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property J() As Byte()
            Get
                Return Me.jField
            End Get
            Set
                Me.jField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property Seed() As Byte()
            Get
                Return Me.seedField
            End Get
            Set
                Me.seedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property PgenCounter() As Byte()
            Get
                Return Me.pgenCounterField
            End Get
            Set
                Me.pgenCounterField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyValueType
        
        Private itemField As Object
        
        Private textField() As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", GetType(DSAKeyValueType)),  _
         System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", GetType(RSAKeyValueType))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class KeyInfoType
        
        Private itemsField() As Object
        
        Private itemsElementNameField() As ItemsChoiceType2
        
        Private textField() As String
        
        Private idField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute(),  _
         System.Xml.Serialization.XmlElementAttribute("KeyName", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("KeyValue", GetType(KeyValueType)),  _
         System.Xml.Serialization.XmlElementAttribute("MgmtData", GetType(String)),  _
         System.Xml.Serialization.XmlElementAttribute("PGPData", GetType(PGPDataType)),  _
         System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", GetType(RetrievalMethodType)),  _
         System.Xml.Serialization.XmlElementAttribute("SPKIData", GetType(SPKIDataType)),  _
         System.Xml.Serialization.XmlElementAttribute("X509Data", GetType(X509DataType)),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")>  _
        Public Property Items() As Object()
            Get
                Return Me.itemsField
            End Get
            Set
                Me.itemsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ItemsElementName"),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemsElementName() As ItemsChoiceType2()
            Get
                Return Me.itemsElementNameField
            End Get
            Set
                Me.itemsElementNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Text() As String()
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema:=false)>  _
    Public Enum ItemsChoiceType2
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("##any:")>  _
        Item
        
        '''<remarks/>
        KeyName
        
        '''<remarks/>
        KeyValue
        
        '''<remarks/>
        MgmtData
        
        '''<remarks/>
        PGPData
        
        '''<remarks/>
        RetrievalMethod
        
        '''<remarks/>
        SPKIData
        
        '''<remarks/>
        X509Data
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureValueType
        
        Private idField As String
        
        Private valueField() As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="base64Binary")>  _
        Public Property Value() As Byte()
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class DigestMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class ReferenceType
        
        Private transformsField() As TransformType
        
        Private digestMethodField As DigestMethodType
        
        Private digestValueField() As Byte
        
        Private idField As String
        
        Private uRIField As String
        
        Private typeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable:=false)>  _
        Public Property Transforms() As TransformType()
            Get
                Return Me.transformsField
            End Get
            Set
                Me.transformsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DigestMethod() As DigestMethodType
            Get
                Return Me.digestMethodField
            End Get
            Set
                Me.digestMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
        Public Property DigestValue() As Byte()
            Get
                Return Me.digestValueField
            End Get
            Set
                Me.digestValueField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property URI() As String
            Get
                Return Me.uRIField
            End Get
            Set
                Me.uRIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureMethodType
        
        Private hMACOutputLengthField As String
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property HMACOutputLength() As String
            Get
                Return Me.hMACOutputLengthField
            End Get
            Set
                Me.hMACOutputLengthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class CanonicalizationMethodType
        
        Private anyField() As System.Xml.XmlNode
        
        Private algorithmField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(),  _
         System.Xml.Serialization.XmlAnyElementAttribute()>  _
        Public Property Any() As System.Xml.XmlNode()
            Get
                Return Me.anyField
            End Get
            Set
                Me.anyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="anyURI")>  _
        Public Property Algorithm() As String
            Get
                Return Me.algorithmField
            End Get
            Set
                Me.algorithmField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignedInfoType
        
        Private canonicalizationMethodField As CanonicalizationMethodType
        
        Private signatureMethodField As SignatureMethodType
        
        Private referenceField() As ReferenceType
        
        Private idField As String
        
        '''<remarks/>
        Public Property CanonicalizationMethod() As CanonicalizationMethodType
            Get
                Return Me.canonicalizationMethodField
            End Get
            Set
                Me.canonicalizationMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignatureMethod() As SignatureMethodType
            Get
                Return Me.signatureMethodField
            End Get
            Set
                Me.signatureMethodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Reference")>  _
        Public Property Reference() As ReferenceType()
            Get
                Return Me.referenceField
            End Get
            Set
                Me.referenceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
    Partial Public Class SignatureType
        
        Private signedInfoField As SignedInfoType
        
        Private signatureValueField As SignatureValueType
        
        Private keyInfoField As KeyInfoType
        
        Private objectField() As ObjectType
        
        Private idField As String
        
        '''<remarks/>
        Public Property SignedInfo() As SignedInfoType
            Get
                Return Me.signedInfoField
            End Get
            Set
                Me.signedInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SignatureValue() As SignatureValueType
            Get
                Return Me.signatureValueField
            End Get
            Set
                Me.signatureValueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property KeyInfo() As KeyInfoType
            Get
                Return Me.keyInfoField
            End Get
            Set
                Me.keyInfoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Object")>  _
        Public Property [Object]() As ObjectType()
            Get
                Return Me.objectField
            End Get
            Set
                Me.objectField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="ID")>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class EnvelopeFooterType
        
        Private signatureField As SignatureType
        
        Private processingField As System.Xml.XmlElement
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.w3.org/2000/09/xmldsig#")>  _
        Public Property Signature() As SignatureType
            Get
                Return Me.signatureField
            End Get
            Set
                Me.signatureField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Processing() As System.Xml.XmlElement
            Get
                Return Me.processingField
            End Get
            Set
                Me.processingField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class ZpracovaniHlaseniType
        
        Private typMaximumField As ZpracovaniVysledekTypType
        
        Private polozkaField() As ZpracovaniHlaseniTypePolozka
        
        '''<remarks/>
        Public Property TypMaximum() As ZpracovaniVysledekTypType
            Get
                Return Me.typMaximumField
            End Get
            Set
                Me.typMaximumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Polozka")>  _
        Public Property Polozka() As ZpracovaniHlaseniTypePolozka()
            Get
                Return Me.polozkaField
            End Get
            Set
                Me.polozkaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class ZpracovaniVysledekTypType
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(PoznamkaType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Poznamka1Type)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ZpracovaniVysledekIDType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ZpracovaniVysledekTextType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ZpracovaniVysledekTypType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(UserNameType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SubjectUnitIdType)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(TextType1)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class TextType
        
        Private jazykKodField As jazykType
        
        Private jazykKodFieldSpecified As Boolean
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property jazykKod() As jazykType
            Get
                Return Me.jazykKodField
            End Get
            Set
                Me.jazykKodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property jazykKodSpecified() As Boolean
            Get
                Return Me.jazykKodFieldSpecified
            End Get
            Set
                Me.jazykKodFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(Poznamka1Type)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class PoznamkaType
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class Poznamka1Type
        Inherits PoznamkaType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class ZpracovaniVysledekIDType
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class ZpracovaniVysledekTextType
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class UserNameType
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class SubjectUnitIdType
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="TextType", [Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class TextType1
        Inherits TextType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class ZpracovaniHlaseniTypePolozka
        
        Private typField As ZpracovaniVysledekTypType
        
        Private idField As ZpracovaniVysledekIDType
        
        Private textField As ZpracovaniVysledekTextType
        
        '''<remarks/>
        Public Property Typ() As ZpracovaniVysledekTypType
            Get
                Return Me.typField
            End Get
            Set
                Me.typField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ID() As ZpracovaniVysledekIDType
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Text() As ZpracovaniVysledekTextType
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class DataTestovaciOdpovedType
        
        Private textZaslanyField As Poznamka1Type
        
        Private datumZaslaneField As DatumType
        
        Private datumCasZaslanyField As DatumCasType
        
        Private castkaZaslanaField As CastkaType
        
        Private priznakZaslanyField As PriznakType
        
        Private zpracovaniVysledekField As ZpracovaniHlaseniType
        
        '''<remarks/>
        Public Property TextZaslany() As Poznamka1Type
            Get
                Return Me.textZaslanyField
            End Get
            Set
                Me.textZaslanyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatumZaslane() As DatumType
            Get
                Return Me.datumZaslaneField
            End Get
            Set
                Me.datumZaslaneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatumCasZaslany() As DatumCasType
            Get
                Return Me.datumCasZaslanyField
            End Get
            Set
                Me.datumCasZaslanyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CastkaZaslana() As CastkaType
            Get
                Return Me.castkaZaslanaField
            End Get
            Set
                Me.castkaZaslanaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PriznakZaslany() As PriznakType
            Get
                Return Me.priznakZaslanyField
            End Get
            Set
                Me.priznakZaslanyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ZpracovaniVysledek() As ZpracovaniHlaseniType
            Get
                Return Me.zpracovaniVysledekField
            End Get
            Set
                Me.zpracovaniVysledekField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class DatumType
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="date")>  _
        Public Property Value() As Date
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class DatumCasType
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As Date
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class CastkaType
        Inherits CenaType
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(CastkaType)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class CenaType
        
        Private menaKodField As String
        
        Private menaCiselnikIDField As String
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property menaKod() As String
            Get
                Return Me.menaKodField
            End Get
            Set
                Me.menaKodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property menaCiselnikID() As String
            Get
                Return Me.menaCiselnikIDField
            End Get
            Set
                Me.menaCiselnikIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As Decimal
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Risre:Types:v1")>  _
    Partial Public Class PriznakType
        Inherits IndikatorXmlType
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(PriznakType)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class IndikatorXmlType
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As Boolean
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class DataTestovaciType
        
        Private textField As Poznamka1Type
        
        Private datumField As DatumType
        
        Private datumCasField As DatumCasType
        
        Private castkaField As CastkaType
        
        Private priznakField As PriznakType
        
        '''<remarks/>
        Public Property Text() As Poznamka1Type
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Datum() As DatumType
            Get
                Return Me.datumField
            End Get
            Set
                Me.datumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DatumCas() As DatumCasType
            Get
                Return Me.datumCasField
            End Get
            Set
                Me.datumCasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Castka() As CastkaType
            Get
                Return Me.castkaField
            End Get
            Set
                Me.castkaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Priznak() As PriznakType
            Get
                Return Me.priznakField
            End Get
            Set
                Me.priznakField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class ZpravaRisreTestovaciType
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("DataTestovaci", GetType(DataTestovaciType)),  _
         System.Xml.Serialization.XmlElementAttribute("DataTestovaciOdpoved", GetType(DataTestovaciOdpovedType)),  _
         System.Xml.Serialization.XmlElementAttribute("ZpracovaniChyba", GetType(ZpracovaniHlaseniType))>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class EnvelopeBodyType
        
        Private itemField As ZpravaRisreTestovaciType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ZpravaRisreTestovaci")>  _
        Public Property Item() As ZpravaRisreTestovaciType
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class AuthenticationType
        
        Private identificationField As TextType1
        
        Private passwordField As TextType1
        
        Private methodField As TextType1
        
        '''<remarks/>
        Public Property Identification() As TextType1
            Get
                Return Me.identificationField
            End Get
            Set
                Me.identificationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As TextType1
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Method() As TextType1
            Get
                Return Me.methodField
            End Get
            Set
                Me.methodField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class RecipientSubjectType
        
        Private itemField As IdentifikatorType
        
        Private subjectUnitIdField As SubjectUnitIdType
        
        Private subjectNameField As TextType
        
        Private moduleField As ModuleType
        
        Private responsiblePersonField As PersonType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("IC", GetType(SubjektICOType), [Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1"),  _
         System.Xml.Serialization.XmlElementAttribute("SubjectId", GetType(SubjectIdType), [Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property Item() As IdentifikatorType
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property SubjectUnitId() As SubjectUnitIdType
            Get
                Return Me.subjectUnitIdField
            End Get
            Set
                Me.subjectUnitIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property SubjectName() As TextType
            Get
                Return Me.subjectNameField
            End Get
            Set
                Me.subjectNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property [Module]() As ModuleType
            Get
                Return Me.moduleField
            End Get
            Set
                Me.moduleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property ResponsiblePerson() As PersonType
            Get
                Return Me.responsiblePersonField
            End Get
            Set
                Me.responsiblePersonField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:BusinessTypes:v2")>  _
    Partial Public Class SubjektICOType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class SubjectIdType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class ModuleType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class PersonType
        
        Private personNameField As TextType
        
        Private emailField As EmailType
        
        Private personIdField As PersonIdType
        
        Private userNameField As UserNameType
        
        Private certificateIdField As KodType
        
        Private phoneNumberField() As FaxTelefonCisloType
        
        '''<remarks/>
        Public Property PersonName() As TextType
            Get
                Return Me.personNameField
            End Get
            Set
                Me.personNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Email() As EmailType
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PersonId() As PersonIdType
            Get
                Return Me.personIdField
            End Get
            Set
                Me.personIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserName() As UserNameType
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CertificateId() As KodType
            Get
                Return Me.certificateIdField
            End Get
            Set
                Me.certificateIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("PhoneNumber")>  _
        Public Property PhoneNumber() As FaxTelefonCisloType()
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CommonTypes:v1")>  _
    Partial Public Class EmailType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
    Partial Public Class PersonIdType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CoreComponentTypes:v1")>  _
    Partial Public Class KodType
        
        Private ciselnikIDField As String
        
        Private ciselnikSpravceIDField As String
        
        Private ciselnikVerzeIDField As String
        
        Private kodJmenoField As String
        
        Private jazykKodField As jazykType
        
        Private jazykKodFieldSpecified As Boolean
        
        Private objektIDField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property ciselnikID() As String
            Get
                Return Me.ciselnikIDField
            End Get
            Set
                Me.ciselnikIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property ciselnikSpravceID() As String
            Get
                Return Me.ciselnikSpravceIDField
            End Get
            Set
                Me.ciselnikSpravceIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property ciselnikVerzeID() As String
            Get
                Return Me.ciselnikVerzeIDField
            End Get
            Set
                Me.ciselnikVerzeIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property kodJmeno() As String
            Get
                Return Me.kodJmenoField
            End Get
            Set
                Me.kodJmenoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property jazykKod() As jazykType
            Get
                Return Me.jazykKodField
            End Get
            Set
                Me.jazykKodField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property jazykKodSpecified() As Boolean
            Get
                Return Me.jazykKodFieldSpecified
            End Get
            Set
                Me.jazykKodFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute(DataType:="token")>  _
        Public Property objektID() As String
            Get
                Return Me.objektIDField
            End Get
            Set
                Me.objektIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute(DataType:="token")>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:isvs:micr:schemas:CommonTypes:v1")>  _
    Partial Public Class FaxTelefonCisloType
        Inherits IdentifikatorType
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Messaging:v1")>  _
    Partial Public Class SenderSubjectType
        
        Private itemField As IdentifikatorType
        
        Private subjectUnitIdField As SubjectUnitIdType
        
        Private subjectNameField As TextType
        
        Private moduleField As ModuleType
        
        Private responsiblePersonField As PersonType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("IC", GetType(SubjektICOType), [Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1"),  _
         System.Xml.Serialization.XmlElementAttribute("SubjectId", GetType(SubjectIdType), [Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property Item() As IdentifikatorType
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property SubjectUnitId() As SubjectUnitIdType
            Get
                Return Me.subjectUnitIdField
            End Get
            Set
                Me.subjectUnitIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property SubjectName() As TextType
            Get
                Return Me.subjectNameField
            End Get
            Set
                Me.subjectNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property [Module]() As ModuleType
            Get
                Return Me.moduleField
            End Get
            Set
                Me.moduleField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="urn:cz:mfcr:iissp:schemas:Common:v1")>  _
        Public Property ResponsiblePerson() As PersonType
            Get
                Return Me.responsiblePersonField
            End Get
            Set
                Me.responsiblePersonField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")>  _
    Public Delegate Sub SI_TESTWS_OUTSyncCompletedEventHandler(ByVal sender As Object, ByVal e As SI_TESTWS_OUTSyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SI_TESTWS_OUTSyncCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Envelope() As EnvelopeType
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),EnvelopeType)
            End Get
        End Property
    End Class
End Namespace
