'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://testportal3.statnipokladna.cz/risre/ws/INBOX")>  _
        Public Property Url() As String
            Get
                Return CType(Me("Url"),String)
            End Get
            Set
                Me("Url") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ClientCertificate() As Global.System.Security.Cryptography.X509Certificates.X509Certificate2
            Get
                Return CType(Me("ClientCertificate"),Global.System.Security.Cryptography.X509Certificates.X509Certificate2)
            End Get
            Set
                Me("ClientCertificate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000000002")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("lr3zr6c5")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ServerCertificate() As Global.System.Security.Cryptography.X509Certificates.X509Certificate2
            Get
                Return CType(Me("ServerCertificate"),Global.System.Security.Cryptography.X509Certificates.X509Certificate2)
            End Get
            Set
                Me("ServerCertificate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CAServer() As Global.System.Security.Cryptography.X509Certificates.X509Certificate2
            Get
                Return CType(Me("CAServer"),Global.System.Security.Cryptography.X509Certificates.X509Certificate2)
            End Get
            Set
                Me("CAServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property CAClient() As Global.System.Security.Cryptography.X509Certificates.X509Certificate2
            Get
                Return CType(Me("CAClient"),Global.System.Security.Cryptography.X509Certificates.X509Certificate2)
            End Get
            Set
                Me("CAClient") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServiceUrl() As String
            Get
                Return CType(Me("ServiceUrl"),String)
            End Get
            Set
                Me("ServiceUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property OtherCertificates() As Global.System.Security.Cryptography.X509Certificates.X509Certificate2Collection
            Get
                Return CType(Me("OtherCertificates"),Global.System.Security.Cryptography.X509Certificates.X509Certificate2Collection)
            End Get
            Set
                Me("OtherCertificates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EU1620000273")>  _
        Public Property SenderResponsiblePersonId() As String
            Get
                Return CType(Me("SenderResponsiblePersonId"),String)
            End Get
            Set
                Me("SenderResponsiblePersonId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Beneš Jiří")>  _
        Public Property SenderResponsiblePersonName() As String
            Get
                Return CType(Me("SenderResponsiblePersonName"),String)
            End Get
            Set
                Me("SenderResponsiblePersonName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("benes@insyco.cz")>  _
        Public Property SenderResponsiblePersonEmail() As String
            Get
                Return CType(Me("SenderResponsiblePersonEmail"),String)
            End Get
            Set
                Me("SenderResponsiblePersonEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00164801")>  _
        Public Property SenderIc() As String
            Get
                Return CType(Me("SenderIc"),String)
            End Get
            Set
                Me("SenderIc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("IN-SY-CO")>  _
        Public Property SenderSubjectName() As String
            Get
                Return CType(Me("SenderSubjectName"),String)
            End Get
            Set
                Me("SenderSubjectName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00006947")>  _
        Public Property RecipientIc() As String
            Get
                Return CType(Me("RecipientIc"),String)
            End Get
            Set
                Me("RecipientIc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Ministerstvo financí")>  _
        Public Property RecipientSubjectName() As String
            Get
                Return CType(Me("RecipientSubjectName"),String)
            End Get
            Set
                Me("RecipientSubjectName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RISRE")>  _
        Public Property RecipientModule() As String
            Get
                Return CType(Me("RecipientModule"),String)
            End Get
            Set
                Me("RecipientModule") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://testportal3.statnipokladna.cz/risre/ws/B_SP_EKIS_FMMD")>  _
        Public Property Url_FMMD() As String
            Get
                Return CType(Me("Url_FMMD"),String)
            End Get
            Set
                Me("Url_FMMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://testportal3.statnipokladna.cz/risre/ws/B_EKIS_SP_ROP")>  _
        Public Property Url_EKIS_SP_ROP() As String
            Get
                Return CType(Me("Url_EKIS_SP_ROP"),String)
            End Get
            Set
                Me("Url_EKIS_SP_ROP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://testportal3.statnipokladna.cz/risre/ws/B_SP_EKIS_ROP")>  _
        Public Property Url_SP_EKIS_ROP() As String
            Get
                Return CType(Me("Url_SP_EKIS_ROP"),String)
            End Get
            Set
                Me("Url_SP_EKIS_ROP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\iissp\")>  _
        Public Property WorkingDirectory() As String
            Get
                Return CType(Me("WorkingDirectory"),String)
            End Get
            Set
                Me("WorkingDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Loging() As Boolean
            Get
                Return CType(Me("Loging"),Boolean)
            End Get
            Set
                Me("Loging") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25000")>  _
        Public Property TimeOut() As Integer
            Get
                Return CType(Me("TimeOut"),Integer)
            End Get
            Set
                Me("TimeOut") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientCertificatePath() As String
            Get
                Return CType(Me("ClientCertificatePath"),String)
            End Get
            Set
                Me("ClientCertificatePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ClientCertificatePWD() As String
            Get
                Return CType(Me("ClientCertificatePWD"),String)
            End Get
            Set
                Me("ClientCertificatePWD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://testportal3.statnipokladna.cz/risre/ws/B_EKIS_SP_ROP_ATT")>  _
        Public Property Url_EKIS_SP_ROP_ATT() As String
            Get
                Return CType(Me("Url_EKIS_SP_ROP_ATT"),String)
            End Get
            Set
                Me("Url_EKIS_SP_ROP_ATT") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.IISSPClassLibrary.My.MySettings
            Get
                Return Global.IISSPClassLibrary.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
